minVersion: 0.23.1
targets:
  - name: pypi
    includeNames: /^sentry[_\-]sdk.*$/
  - name: github
  - name: gh-pages
  - name: registry
    sdks:
      pypi:sentry-sdk:
  - name: aws-lambda-layer
    includeNames: /^sentry-python-serverless-\d+(\.\d+)*\.zip$/
    layerName: SentryPythonServerlessSDK
    compatibleRuntimes:
      - name: python
        versions:
          - python2.7
          - python3.6
          - python3.7
          - python3.8
    license: MIT
changelog: CHANGELOG.md
changelogPolicy: simple
