---
minVersion: '0.5.1'
github:
  owner: getsentry
  repo: sentry-python
targets: 
  - name: pypi
  - name: github
  - name: gh-pages
  - name: registry
    type: sdk
    config:
      canonical: pypi:sentry-sdk
