---
minVersion: "0.14.0"
github:
  owner: getsentry
  repo: sentry-python

targets:
  - name: pypi
  - name: github
  - name: gh-pages
  - name: registry
    type: sdk
    config:
      canonical: pypi:sentry-sdk

changelog: CHANGES.md
changelogPolicy: simple

statusProvider:
  name: github
artifactProvider:
  name: github
