coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit
        threshold: 10%  # this allows a 10% drop from the previous base commit coverage
        informational: true

ignore:
  - "tests"
  - "sentry_sdk/_types.py"

# Read more here: https://docs.codecov.com/docs/pull-request-comments
comment:
  # This is the addition of carry forward builds and fresh builds, thus, it's the addition
  # of the FE and BE builds
  after_n_builds: 100
  layout: 'diff, files'
  # Update, if comment exists. Otherwise post new.
  behavior: default
  # Comments will only post when coverage changes. Furthermore, if a comment
  # already exists, and a newer commit results in no coverage change for the
  # entire pull, the comment will be deleted.
  require_changes: true
  require_base: true # must have a base report to post
  require_head: true # must have a head report to post
  require_bundle_changes: True # only post a comment when there are bundle size changes

github_checks:
  annotations: false