# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tests.integrations.grpc.grpc_aio_test_service_pb2 as grpc__aio__test__service__pb2


class gRPCaioTestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestServe = channel.unary_unary(
            "/grpc_aio_test_server.gRPCaioTestService/TestServe",
            request_serializer=grpc__aio__test__service__pb2.gRPCaioTestMessage.SerializeToString,
            response_deserializer=grpc__aio__test__service__pb2.gRPCaioTestMessage.FromString,
        )


class gRPCaioTestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestServe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_gRPCaioTestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TestServe": grpc.unary_unary_rpc_method_handler(
            servicer.TestServe,
            request_deserializer=grpc__aio__test__service__pb2.gRPCaioTestMessage.FromString,
            response_serializer=grpc__aio__test__service__pb2.gRPCaioTestMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "grpc_aio_test_server.gRPCaioTestService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class gRPCaioTestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestServe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grpc_aio_test_server.gRPCaioTestService/TestServe",
            grpc__aio__test__service__pb2.gRPCaioTestMessage.SerializeToString,
            grpc__aio__test__service__pb2.gRPCaioTestMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
