name: Changelog Preview
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
    - unlabeled
permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@25028d0646040cc0a669ae3314cbf884f4c4347a # v2
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
