name: CI

on:
  push:
    branches:
      - master
      - release/**

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist-serverless

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      has_code_changes: ${{ steps.changes.outputs.has_code_changes }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            has_code_changes:
              - 'sentry_sdk/**'
              - 'tests/**'
              - 'scripts/**'
              - '**/*.py'
              - '**/*.cfg'
              - '**/*.toml'
              - '**/*.ini'
              - 'Makefile'
              - 'requirements*.txt'
              - '.github/workflows/**'

  lint:
    needs: changes
    if: needs.changes.outputs.has_code_changes == 'true'
    name: Lint Sources
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.14

      - run: |
          pip install tox
          tox -e linters

  build_lambda_layer:
    needs: changes
    if: needs.changes.outputs.has_code_changes == 'true'
    name: Build Package
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.12
      - name: Setup build cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: build_cache
        with:
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ env.BUILD_CACHE_KEY }}
      - name: Build Packages
        run: |
          echo "Creating directory containing Python SDK Lambda Layer"
          # This will also trigger "make dist" that creates the Python packages
          make aws-lambda-layer
      - name: Upload Python Packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-build_lambda_layer
          path: |
            dist/*
          if-no-files-found: 'error'

  docs:
    needs: changes
    if: needs.changes.outputs.has_code_changes == 'true'
    name: Build SDK API Doc
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.12

      - run: |
          make apidocs
          cd docs/_build && zip -r gh-pages ./

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-docs
          path: |
            docs/_build/gh-pages.zip
          if-no-files-found: 'error'

  check_required_ci:
    name: All CI checks passed
    needs: [changes, lint, build_lambda_layer, docs]
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Check for failures
        if: |
          needs.changes.result == 'failure' || needs.changes.result == 'cancelled' ||
          needs.lint.result == 'failure' || needs.lint.result == 'cancelled' ||
          needs.build_lambda_layer.result == 'failure' || needs.build_lambda_layer.result == 'cancelled' ||
          needs.docs.result == 'failure' || needs.docs.result == 'cancelled'
        run: |
          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
