name: CI

on:
  push:
    branches:
      - master
      - release/**

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint Sources
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.14

      - name: Ruff check
        run: uv run ruff check tests sentry_sdk

      - name: Ruff format
        run: uv run ruff format --check tests sentry_sdk

      - name: Find raise from None
        run: uv run python scripts/find_raise_from_none.py

      - name: Mypy
        run: uv run --group typing mypy sentry_sdk

  build_lambda_layer:
    name: Build Package
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.14
      - name: Build Packages
        run: |
          echo "Building SDK dist wheel and tar.gz"
          uv build
          echo "Building AWS Lambda Layer"
          uv run --group aws --with-editable . python scripts/build_aws_lambda_layer.py
      - name: Upload Python Packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-build_lambda_layer
          path: |
            dist/*
          if-no-files-found: 'error'

  docs:
    name: Build SDK API Doc
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.14

      - run: |
          rm -rf docs/_build
          uv run --group docs sphinx-build -vv -W -b html docs/ docs/_build
          cd docs/_build && zip -r gh-pages ./

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-docs
          path: |
            docs/_build/gh-pages.zip
          if-no-files-found: 'error'
