name: dist

on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  dist:
    name: distribution packages
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: make ci-upload-dist
