name: Enforce License Compliance

on:
  push:
    branches:
      - master
      - main
      - release/*
      - sentry-sdk-2.0
  pull_request:
    branches:
      - master
      - main
      - sentry-sdk-2.0

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@main
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
