name: Create JIRA issue

on:
  issues:
    types: [labeled]

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: getsentry/ga-jira-integration@main
        with:
          JIRA_API_HOST: ${{secrets.JIRA_BASEURL}}
          JIRA_API_TOKEN: ${{secrets.JIRA_APITOKEN}}
          JIRA_EMAIL: ${{secrets.JIRA_USEREMAIL}}
          TRIGGER_LABEL: "Jira"
          JIRA_PROJECT_ID: WEBBACKEND
          JIRA_ISSUE_NAME: Story
