name: lint

on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install tox

      - run: tox -e linters

