name: Python tests

on:
  push:
    branches: [master]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  linters:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install tox
      - run: tox -e linters

  tests:
    runs-on: ubuntu-16.04
    services:
      postgresql:
        image: postgres:10.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python:
          - "2.7"
          - "pypy2"
          - "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        env:
          SENTRY_PYTHON_TEST_POSTGRES_USER: postgres
          SENTRY_PYTHON_TEST_POSTGRES_NAME: postgres
        run: |
          python -m pip install -U pip
          pip install tox
          pip install codecov
          bash scripts/download-semaphore.sh
          coverage erase
      - name: Tox
        run: ./scripts/runtox.sh '' --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Report coverage
        run: |
          coverage combine .coverage*
          coverage xml -i
          codecov --file coverage.xml
