name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (or "auto")
        required: false
      force:
        description: Force a release even when there are release-blockers
        required: false
      merge_target:
        description: Target branch to merge into
        required: false
permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release a new version
    steps:
    - name: Get auth token
      id: token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        app-id: ${{ vars.SENTRY_RELEASE_BOT_CLIENT_ID }}
        private-key: ${{ secrets.SENTRY_RELEASE_BOT_PRIVATE_KEY }}
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        token: ${{ steps.token.outputs.token }}
        fetch-depth: 0
    - name: Prepare release
      uses: getsentry/craft@4468eb9e399655a61c770534dacc03139d98aa18 # v2.26.8
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
      with:
        version: ${{ inputs.version }}
        force: ${{ inputs.force }}
        merge_target: ${{ inputs.merge_target }}
