name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (or "auto")
        required: false
      force:
        description: Force a release even when there are release-blockers
        required: false
      merge_target:
        description: Target branch to merge into
        required: false
permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release a new version
    steps:
    - name: Get auth token
      id: token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        app-id: ${{ vars.SENTRY_RELEASE_BOT_CLIENT_ID }}
        private-key: ${{ secrets.SENTRY_RELEASE_BOT_PRIVATE_KEY }}
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        token: ${{ steps.token.outputs.token }}
        fetch-depth: 0
    - name: Prepare release
      uses: getsentry/craft@cdb657d4bbc70cd497876ad158984b4d345a48ae # 2.26.14
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
      with:
        version: ${{ inputs.version }}
        force: ${{ inputs.force }}
        merge_target: ${{ inputs.merge_target }}
