name: Test flask

on:
  push:
    branches:
      - master
      - release/**

  pull_request:

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist-serverless

jobs:
  test:
    name: flask, python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5","3.6","3.7","3.8","3.9","3.10","3.11"]
        # python3.6 reached EOL and is no longer being supported on
        # new versions of hosted runners on Github Actions
        # ubuntu-20.04 is the last version that supported python3.6
        # see https://github.com/actions/setup-python/issues/544#issuecomment-1332535877
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Test Env
        run: |
          pip install coverage "tox>=3,<4"

      - name: Test flask
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 2
          retry_wait_seconds: 5
          shell: bash
          command: |
            set -x # print commands that are executed
            coverage erase

            # Run tests
            ./scripts/runtox.sh "py${{ matrix.python-version }}-flask" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch &&
            coverage combine .coverage* &&
            coverage xml -i

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

  test-py27:
    name: flask, python 2.7, ubuntu-20.04
    runs-on: ubuntu-20.04
    container: python:2.7
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Test Env
        run: |
          pip install coverage "tox>=3,<4"

      - name: Test flask
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 2
          retry_wait_seconds: 5
          shell: bash
          command: |
            set -x # print commands that are executed
            coverage erase

            # Run tests
            ./scripts/runtox.sh "py2.7-flask" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch &&
            coverage combine .coverage* &&
            coverage xml -i

  check_required_tests:
    name: All flask tests passed or skipped
    needs: [test, test-py27]
    # Always run this, even if a dependent job failed
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: Check for failures
        if: contains(needs.test.result, 'failure')
        run: |
          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
      - name: Check for 2.7 failures
        if: contains(needs.test-py27.result, 'failure')
        run: |
          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
