name: Test Django

on:
  push:
    branches:
      - master
      - release/**
      - antonpirker/**

  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test Django ${{ matrix.django-version }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        django-version: ["2.0", "2.1", "2.2", "3.0", "3.1", "3.2", "3.3", "4.0", "4.1"]
        include:
          - python-version: "2.7"
            django-version: "1.8"
          - python-version: "2.7"
            django-version: "1.9"
          - python-version: "2.7"
            django-version: "1.10"
          - python-version: "2.7"
            django-version: "1.11"
          - python-version: "3.5"
            django-version: "1.8"
          - python-version: "3.5"
            django-version: "1.9"
          - python-version: "3.5"
            django-version: "1.10"
          - python-version: "3.5"
            django-version: "1.11"
          - python-version: "3.5"
            django-version: "2.0"
          - python-version: "3.5"
            django-version: "2.1"
          - python-version: "3.6"
            django-version: "2.0"
          - python-version: "3.6"
            django-version: "2.1"
        # python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        # django-version: ["1.8", "1.9", "1.10", "1.11", "2.0", "2.1", "2.2", "3.0", "3.1", "3.2", "3.3", "4.0", "4.1"]
        # exclude:
        # - python-version: "2.7"
        #   django-version: "2.0"
        # - python-version: "2.7"
        #   django-version: "2.1"
        # - python-version: "2.7"
        #   django-version: "2.2"
        # - python-version: "2.7"
        #   django-version: "3.0"
        # - python-version: "2.7"
        #   django-version: "3.1"
        # - python-version: "2.7"
        #   django-version: "3.2"
        # - python-version: "2.7"
        #   django-version: "3.3"
        # - python-version: "2.7"
        #   django-version: "4.0"
        # - python-version: "2.7"
        #   django-version: "4.1"
        # - python-version: "3.5"
        #   django-version: "2.2"
        # - python-version: "3.5"
        #   django-version: "3.0"
        # - python-version: "3.5"
        #   django-version: "3.1"
        # - python-version: "3.5"
        #   django-version: "3.2"
        # - python-version: "3.5"
        #   django-version: "3.3"
        # - python-version: "3.5"
        #   django-version: "4.0"
        # - python-version: "3.5"
        #   django-version: "4.1"
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          echo "Running tests for Django ${{ matrix.django-version }} / Python ${{ matrix.python-version }}"
