name: test

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist-serverless

jobs:
  test-py311:
    name: Test Python 3.11
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python --version

      - name: Setup Test Env
        run: |
          pip install "tox>=3,<4"

      - name: Test x
        timeout-minutes: 45
        shell: bash
        run: |
          set -x # print commands that are executed

          ./scripts/runtox.sh "3.11"

  test-py311-ubuntu2004:
    name: Test Python 3.11 Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python --version

      - name: Setup Test Env
        run: |
          pip install "tox>=3,<4"

      - name: Test x
        timeout-minutes: 45
        shell: bash
        run: |
          set -x # print commands that are executed

          ./scripts/runtox.sh "3.11"
