name: Test Django

on:
  push:
    branches:
      - master
      - release/**
      - antonpirker/**

  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test Django ${{ matrix.django-version }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.linux-version }}
    timeout-minutes: 45
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10]
        django: [1.8, 1.9, 1.10, 1.11, 2.0, 2.1, 2.2, 3.0, 3.1, 3.2, 3.3, 4.0, 4.1]
        include:
          - { os: ubuntu-latest, python: 2.7, django: 1.8 }
          - { os: ubuntu-latest, python: 2.7, django: 1.9 }
          - { os: ubuntu-latest, python: 2.7, django: 1.10 }
          - { os: ubuntu-latest, python: 2.7, django: 1.11 }

          - { os: ubuntu-latest, python: 3.5, django: 1.8 }
          - { os: ubuntu-latest, python: 3.5, django: 1.9 }
          - { os: ubuntu-latest, python: 3.5, django: 1.10 }
          - { os: ubuntu-latest, python: 3.5, django: 1.11 }
          - { os: ubuntu-latest, python: 3.5, django: 2.0 }
          - { os: ubuntu-latest, python: 3.5, django: 2.1 }
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          echo "Running the tests"
