name: CI

on:
  push:
    branches:
      - master
      - release/**
      - antonpirker/**

  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test Django ${{ matrix.python-version }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.linux-version }}
    timeout-minutes: 45
    continue-on-error: true
    strategy:
      matrix:
        linux-version: [ubuntu-latest]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        django-version: [1.8, 1.9, 1.10, 1.11, 2.0, 2.1, 2.2, 3.0, 3.1, 3.2, 3.3, 4.0, 4.1]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: |
          echo "Running the tests"
